image: node:20

before_script:
  - git submodule update --init --recursive

stages:
  - install
  - build
  - validate
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

build_project:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
  dependencies:
    - install_dependencies

validate_artifact:
  stage: validate
  script:
    - npm run lint
  dependencies:
    - install_dependencies
    - build_project

pages:
  stage: deploy
  script:
    - rm -rf public && mkdir public
    - mv dist/* public/
    - ls -l public
  artifacts:
    paths:
      - public
